import { Dimensions, StyleSheet } from "react-native";
import {
    DARK_GRAY,
    BACKGROUND_WHITE,
    BACKGROUND_GRAY,
    CANCEL_RED,
    BOX_WHITE,
    BACKGROUND_DARK,
    ACT_WHITE,
    appFontExtraBold,
    appFontBold,
    appFontBook,
    LOGO_RED,
    BOX_RED,
    SYNC_GRAY,
    LIGHT_GRAY,
    GRAY,
    ALT_RED,
    RED,
    HEADER_RED,
    BACKGROUND_RED,
    BLACK,
    WHITE
} from "../constants";
import { moderateScale, scale } from "react-native-size-matters";
const windowWidth = Dimensions.get("window").width;

export const routingStyle = StyleSheet.create({
    labelStyles: {
        fontSize: moderateScale(18),
        fontFamily: appFontBold,
        color: BOX_WHITE,
    },
    activeLabelStyles: {
        fontSize: moderateScale(18),
        fontFamily: appFontBold,
        color: WHITE,
    },
    offlinelabelStyles: {
        fontSize: moderateScale(18),
        fontFamily: appFontBold,
        color: BOX_WHITE,
        textDecorationLine: "line-through",
    },
    itemStyles: {
        height: scale(60),
        borderTopWidth: 0.5,
        borderBottomWidth: 0.5,
        borderColor: BACKGROUND_WHITE,
        backgroundColor: DARK_GRAY,
    },
    offlineItemStyles: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-around",
        height: moderateScale(50),
        width: "100%",
        borderBottomWidth: moderateScale(2),
        borderColor: SYNC_GRAY,
        backgroundColor: BACKGROUND_GRAY,
    },
    onlineItemStyles: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        height: moderateScale(50),
        width: "100%",
        borderBottomWidth: moderateScale(2),
        borderColor: CANCEL_RED,
        backgroundColor: LOGO_RED,
    },
    activeOfflineItemStyles: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-around",
        height: moderateScale(50),
        width: "100%",
        borderBottomWidth: moderateScale(2),
        borderColor: SYNC_GRAY,
        backgroundColor: GRAY,
    },
    activeOnlineItemStyles: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        height: moderateScale(50),
        width: "100%",
        borderBottomWidth: moderateScale(2),
        borderColor: CANCEL_RED,
        backgroundColor: BOX_RED,
    },
    iconContainerStyles: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: BOX_WHITE,
        height: moderateScale(35),
        width: moderateScale(35),
        borderRadius: moderateScale(25),
    },
    activeIconContainerStyles: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: WHITE,
        height: moderateScale(35),
        width: moderateScale(35),
        borderRadius: moderateScale(25),
    },
    containerStyles: {
        flex: 1,
        flexDirection: "column",
    },
    headerStyles: {
        height: "100%",
        width: windowWidth,
        display: "flex",
        flexDirection: "row",
        backgroundColor: CANCEL_RED,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: 'center',
        paddingHorizontal: 8
    },
    headerLabelStyles: {
        fontSize: moderateScale(18),
        color: WHITE,
        fontFamily: appFontBold
    },
    medHeaderStyles: {
        height: "100%",
        width: windowWidth,
        display: "flex",
        flexDirection: "row",
        paddingHorizontal: 8
    },
    medHeaderLabelStyles: {
        fontSize: 18,
        fontFamily: appFontBold,
        width: "100%",
        textAlign: "center",
        color: WHITE,
    },
});
